# Generated by Django 6.1 on 2026-08-26 20:39

import django.db.models.deletion
import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=64)),
                ("caption", models.CharField(blank=True, max_length=255)),
                ("kind", models.CharField(default="other", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EpisodeActionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("podcast", models.TextField()),
                ("episode", models.TextField()),
                ("guid", models.CharField(blank=True, default="", max_length=255)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("new", "new"),
                            ("download", "download"),
                            ("play", "play"),
                            ("delete", "delete"),
                        ],
                        max_length=8,
                    ),
                ),
                ("happened_at", models.DateTimeField()),
                ("started", models.IntegerField(blank=True, null=True)),
                ("position", models.IntegerField(blank=True, null=True)),
                ("total", models.IntegerField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="episode_actions",
                        to="gpodsync.device",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SubscriptionChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("url", models.TextField()),
                (
                    "action",
                    models.CharField(
                        choices=[("add", "subscribed"), ("remove", "unsubscribed")],
                        max_length=6,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_changes",
                        to="gpodsync.device",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="device",
            constraint=models.UniqueConstraint(
                fields=("user", "device_id"), name="unique_device_per_user"
            ),
        ),
        migrations.AddIndex(
            model_name="episodeactionrecord",
            index=models.Index(fields=["user", "id"], name="gpodsync_ep_user_id_3ef4f0_idx"),
        ),
        migrations.AddConstraint(
            model_name="episodeactionrecord",
            constraint=models.UniqueConstraint(
                models.F("user"),
                models.F("podcast"),
                models.F("episode"),
                models.F("action"),
                models.F("happened_at"),
                models.F("guid"),
                django.db.models.functions.comparison.Coalesce("started", models.Value(-1)),
                django.db.models.functions.comparison.Coalesce("position", models.Value(-1)),
                django.db.models.functions.comparison.Coalesce("total", models.Value(-1)),
                name="one_row_per_reported_moment",
            ),
        ),
        migrations.AddIndex(
            model_name="subscriptionchange",
            index=models.Index(
                fields=["user", "device", "id"], name="gpodsync_su_user_id_0abc04_idx"
            ),
        ),
    ]
